# Generated by Django 3.2.5 on 2021-10-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='post',
        ),
        migrations.AddField(
            model_name='community',
            name='fb_group',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
