# Generated by Django 3.2.5 on 2021-10-07 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0004_post_thana'),
        ('community', '0005_auto_20211007_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responses',
            new_name='MakeRequest',
        ),
    ]
