# Generated by Django 3.2.5 on 2021-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isDonor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=None, max_length=55),
            preserve_default=False,
        ),
    ]
