# Generated by Django 3.2.5 on 2021-09-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_auto_20210922_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thana',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
